#dependabot configuration for NPM

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"
    groups:
      lint:
        patterns:
          - "eslint*"
          - "@eslint*"
          - "globals"
          - "typescript-eslint*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
