name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - ".github/**"
      
# Allow one concurrent deployment
concurrency:
  group: "glitch"
  cancel-in-progress: true

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v3
      with:
        source_repo: "https://github.com/dan-mba/url-shortener.git"
        source_branch: "main"
        destination_repo: ${{ secrets.glitch_git_URL }}
        destination_branch: "master"
